# Generated by Django 3.0.10 on 2020-10-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_basket_position_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='amount',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='Наименование'),
        ),
    ]
