# Generated by Django 3.0.10 on 2020-10-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201018_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='last_name',
            new_name='title',
        ),
    ]
